//
// Created by basti on 03.11.2020.
//

#ifndef PRODUCTION_LINE_SIMULATOR_VERSION_H
#define PRODUCTION_LINE_SIMULATOR_VERSION_H

#define VERSION_MAJOR     0
#define VERSION_MINOR     5
#define VERSION_REVISION  1

#endif //PRODUCTION_LINE_SIMULATOR_VERSION_H
